### PR TITLE
Update to 0.0.7

### PR DESCRIPTION
**Pull request by samwaseda**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
> Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)

?

**Comment by samwaseda** [comment]
> > Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
> 
> ?

Ah shit

**Comment by jan-janssen** [comment]
The issue is that the new version is now already uploaded, even before merging the pull request: https://anaconda.org/conda-forge/mamonca/files

**Comment by samwaseda** [comment]
> The issue is that the new version is now already uploaded, even before merging the pull request: https://anaconda.org/conda-forge/mamonca/files

Ah that’s probably because I accidentally merged it to `main`. Should I change it to 0.0.8?

**Pull request closed without merging**
